version: '3.8'

services:
  backend:
    image: backend
    build:
      context: ./DotnetProject
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AAS_SERVICE_URL=http://host.docker.internal:8081
    networks:
      - my_custom_network
    extra_hosts:
      - "HostOfYourOPCUADevice:IPAddressOfOPCAUYourDevice"

  angular-app:
    build:
      context: ./angular-project
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - my_custom_network
    depends_on:
      - backend

networks:
  my_custom_network:
    external: true 