version: '3.8'

services:
  dotnet-api:
    build:
      context: ./DotnetProject
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network

  
  # angular-app:
  #   build:
  #     context: ./angular-project
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - my-network

networks:
  my-network:
    driver: bridge