version: "3.9"
services:
  mongo:
    image: mongo:5.0.10
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5
    networks:
      - my_custom_network
      
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    volumes:
      - ./aas-env.properties:/application/application.properties
      - ./aas:/application/aas
    ports:
      - 0.0.0.0:8081:8081
    networks:
      - my_custom_network
    depends_on:
        mongo:
            condition: service_healthy
        aas-registry:
            condition: service_healthy
        sm-registry:
            condition: service_healthy            

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    ports:
      - 8082:8080
    volumes:
      - ./aas-registry.yml:/workspace/config/application.yml
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - my_custom_network

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    ports:
      - 8083:8080
    volumes:
      - ./sm-registry.yml:/workspace/config/application.yml
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - my_custom_network

  aas-discovery:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    ports:
      - 8084:8081
    volumes:
      - ./aas-discovery.properties:/application/application.properties
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - my_custom_network


  aas-web-ui_v2:
    image: eclipsebasyx/aas-gui:v2-240327
    container_name: aas-web-ui_v2
    ports:
      - 3000:3000
    environment:
      VITE_AAS_REGISTRY_PATH: "http://localhost:8082"
      VITE_SUBMODEL_REGISTRY_PATH: "http://localhost:8083"
      VITE_AAS_DISCOVERY_PATH: "http://localhost:8084"
      VITE_AAS_REPO_PATH: "http://localhost:8081/shells"
      VITE_SUBMODEL_REPO_PATH: "http://localhost:8081/submodels"

    restart: always


networks:
  my_custom_network:
    external: true